name = "calc"
description = ""
version = "0.1.0-dev"

authors = ["Eyad"]
maintainers = ["Eyad <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["calc"]
